// This file is autogenerated by codegen/rust/node_file.liquid

use crate::nodes::InnerNode;
use crate::nodes::InspectVec;
use crate::Loc;
use crate::Node;

/// Represents a hash literal (i.e. `{ foo: 42 }`)
#[derive(Debug, Clone, PartialEq)]
#[repr(C)]
pub struct Hash {
    /// A list of key-value pairs
    pub pairs: Vec<Node>,

    /// Location of the open parenthesis
    ///
    /// ```text
    /// { a: 1 }
    /// ~
    /// ```
    ///
    /// `None` if hash literal is implicit, e.g. `foo(key: "value")`
    pub begin_l: Option<Loc>,

    /// Location of the closing parenthesis
    ///
    /// ```text
    /// { a: 1 }
    ///        ~
    /// ```
    ///
    /// `None` if hash literal is implicit, e.g. `foo(key: "value")`
    pub end_l: Option<Loc>,

    /// Location of the full expression
    ///
    /// ```text
    /// { a: 1 }
    /// ~~~~~~~~
    /// ```
    pub expression_l: Loc,

}

impl InnerNode for Hash {
    fn expression(&self) -> &Loc {
        &self.expression_l
    }

    fn inspected_children(&self, indent: usize) -> Vec<String> {
        let mut result = InspectVec::new(indent);
        result.push_nodes(&self.pairs);
        
        result.strings()
    }

    fn str_type(&self) -> &'static str {
        "hash"
    }

    fn print_with_locs(&self) {
        println!("{}", self.inspect(0));
        for node in self.pairs.iter() { node.inner_ref().print_with_locs(); }
        if let Some(loc) = self.begin_l.as_ref() { loc.print("begin") }
        if let Some(loc) = self.end_l.as_ref() { loc.print("end") }
        self.expression_l.print("expression");
        
    }
}
