// This file is autogenerated by codegen/rust/node_file.liquid

use crate::nodes::InnerNode;
use crate::nodes::InspectVec;
use crate::Loc;
use crate::Node;

/// Represents pattern matching using one of the given patterns (i.e. `foo in 1 | 2`)
#[derive(Debug, Clone, PartialEq)]
#[repr(C)]
pub struct MatchAlt {
    /// Left pattern
    pub lhs: Box<Node>,

    /// Right pattern
    pub rhs: Box<Node>,

    /// Location of the `|` operator
    ///
    /// ```text
    /// foo in 1 | 2
    ///          ~
    /// ```
    pub operator_l: Loc,

    /// Location of the full expression
    ///
    /// ```text
    /// foo in 1 | 2
    ///        ~~~~~
    /// ```
    pub expression_l: Loc,

}

impl InnerNode for MatchAlt {
    fn expression(&self) -> &Loc {
        &self.expression_l
    }

    fn inspected_children(&self, indent: usize) -> Vec<String> {
        let mut result = InspectVec::new(indent);
        result.push_node(&self.lhs);
        result.push_node(&self.rhs);
        
        result.strings()
    }

    fn str_type(&self) -> &'static str {
        "match_alt"
    }

    fn print_with_locs(&self) {
        println!("{}", self.inspect(0));
        self.lhs.inner_ref().print_with_locs();
        self.rhs.inner_ref().print_with_locs();
        self.operator_l.print("operator");
        self.expression_l.print("expression");
        
    }
}
