// This file is autogenerated by codegen/rust/node_file.liquid

use crate::nodes::InnerNode;
use crate::nodes::InspectVec;
use crate::Loc;


/// Represents `retry` keyword
#[derive(Debug, Clone, PartialEq)]
#[repr(C)]
pub struct Retry {
    /// Location of the `retry` keyword
    ///
    /// ```text
    /// retry
    /// ~~~~~
    /// ```
    pub expression_l: Loc,

}

impl InnerNode for Retry {
    fn expression(&self) -> &Loc {
        &self.expression_l
    }

    fn inspected_children(&self, indent: usize) -> Vec<String> {
        let mut result = InspectVec::new(indent);
        
        result.strings()
    }

    fn str_type(&self) -> &'static str {
        "retry"
    }

    fn print_with_locs(&self) {
        println!("{}", self.inspect(0));
        self.expression_l.print("expression");
        
    }
}
