// This file is autogenerated by codegen/rust/node_file.liquid

use crate::nodes::InnerNode;
use crate::nodes::InspectVec;
use crate::Loc;
use crate::Node;

/// Represents an arguments splat (i.e. `*bar` in a call like `foo(*bar)`)
#[derive(Debug, Clone, PartialEq)]
#[repr(C)]
pub struct Splat {
    /// Value that is converted to array
    pub value: Option<Box<Node>>,

    /// Location of the `*` operator
    ///
    /// ```text
    /// foo(*bar)
    ///     ~
    /// ```
    pub operator_l: Loc,

    /// Location of the full expression
    ///
    /// ```text
    /// foo(*bar)
    ///     ~~~~
    /// ```
    pub expression_l: Loc,

}

impl InnerNode for Splat {
    fn expression(&self) -> &Loc {
        &self.expression_l
    }

    fn inspected_children(&self, indent: usize) -> Vec<String> {
        let mut result = InspectVec::new(indent);
        result.push_maybe_node(&self.value);
        
        result.strings()
    }

    fn str_type(&self) -> &'static str {
        "splat"
    }

    fn print_with_locs(&self) {
        println!("{}", self.inspect(0));
        if let Some(node) = self.value.as_ref() { node.inner_ref().print_with_locs() }
        self.operator_l.print("operator");
        self.expression_l.print("expression");
        
    }
}
