pub const STR_FUNC_ESCAPE: i32 = 0x01;
pub const STR_FUNC_EXPAND: i32 = 0x02;
pub const STR_FUNC_REGEXP: i32 = 0x04;
pub const STR_FUNC_QWORDS: i32 = 0x08;
pub const STR_FUNC_SYMBOL: i32 = 0x10;
pub const STR_FUNC_INDENT: i32 = 0x20;
pub const STR_FUNC_LABEL : i32 = 0x40;
pub const STR_FUNC_LIST  : i32 = 0x4000;
pub const STR_FUNC_TERM  : i32 = 0x8000;

pub const str_label : i32 = STR_FUNC_LABEL;
pub const str_squote: i32 = 0;
pub const str_dquote: i32 = STR_FUNC_EXPAND;
pub const str_xquote: i32 = STR_FUNC_EXPAND;
pub const str_regexp: i32 = STR_FUNC_REGEXP|STR_FUNC_ESCAPE|STR_FUNC_EXPAND;
pub const str_sword : i32 = STR_FUNC_QWORDS|STR_FUNC_LIST;
pub const str_dword : i32 = STR_FUNC_QWORDS|STR_FUNC_EXPAND|STR_FUNC_LIST;
pub const str_ssym  : i32 = STR_FUNC_SYMBOL;
pub const str_dsym  : i32 = STR_FUNC_SYMBOL|STR_FUNC_EXPAND;
