name: post-release

# on:
#   push:
#     tags:
#       - 'v*'
on:
  push:
    branches: [ master ]

jobs:
  post-release:
    name: create post-release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: bison-packages/install-bison@v1
        with:
          version: '3.8.2'

      - run: cargo check --features=development
      - run: cargo run --bin dump_token_ids

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: v4.0.5
          artifacts: target/tokens
          token: ${{ secrets.GITHUB_TOKEN }}
