name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-F unsafe_code"

jobs:
  test:
    name: test c interop layer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rustflags:
          - "-Zsanitizer=address"
          - "-Zsanitizer=hwaddress"
          - "-Zsanitizer=leak"
          - "-Zsanitizer=memory"

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: install bison
        run: |
          sudo apt-get update
          sudo apt-get install bison

      - name: print bison version
        run: bison --version

      - name: codegen
        run: cargo build --features rebuild-grammar

      - name: run tests
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cargo test --features c-structures --tests -- --nocapture
