name: test-rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-F unsafe_code"

jobs:
  test:
    name: test on ${{ matrix.build.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - { rust: stable,  cargoargs: "--features onig" }
          - { rust: beta,    cargoargs: "--features onig" }
          # nightly is somewhat broken:
          # 1. there's a bug with string escaping
          # 2. it fails to compile onig
          - { rust: nightly, cargoargs: "--test parser_test" }

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.build.rust }}
          override: true

      - name: install bison
        run: |
          brew update
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: show bison version
        run: bison --version

      - name: codegen
        run: cargo build --features rebuild-grammar

      - name: run tests
        run: cargo test ${{ matrix.build.cargoargs }} -- --nocapture
